config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'posts/home'

  get 'pages/aboutMe'

  get 'fileuploads/index'

  get 'fileuploads/show'

  get 'posts/index'

  resources :posts, :projects, :languages, :fileuploads

  resources :fileuploads, path: "index" do
    collection do
      get :by_language
    end
  end

  
  root 'posts#home'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fileupload.rb
class Fileupload < ActiveRecord::Base

	belongs_to :language

	extend FriendlyId
	friendly_id :title, use: :slugged

=begin
	has_attached_file :code,
		:storage => :google_drive,
		:google_drive_credentials => "#{Rails.root}/config/google_drive.yml",
		:google_drive_options => {
				:public_folder_id => '0B5D6lx1xpqw2eG96Ylc2aklGeVE'
		}
=end
	has_one_attached :upload


	scope  :by_language, ->(sort){ where :language_id => sort }

end

app/models/language.rb
class Language < ApplicationRecord

  has_many :fileuploads

end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fileuploads_controller.rb
class FileuploadsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index, :by_language]
  before_action :find_fileupload, only: [:show, :edit, :update, :destroy]

  def edit
  end

  def index
    @fileuploads = Fileupload.all.order("created_at desc").paginate(page: params[:page], per_page: 15)
  end

  def by_language

    @fileuploads = Fileupload.by_language(params[:sort]).order("created_at desc").paginate(page: params[:page], per_page: 15) if params[:sort].present?
    render action: "index"
  end

  def new
    @fileupload=Fileupload.new
  end

  def create
    @fileupload = Fileupload.new(fileupload_params)

    if @fileupload.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def update
    if @fileupload.update(fileupload_params)
      @fileupload.upload.attach(params[:fileupload][:upload])
      redirect_to action: "index"
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @fileupload.destroy
    redirect_to action: "index"
  end

  private

    def find_fileupload
      @fileupload = Fileupload.friendly.find(params[:id])
    end

    def fileupload_params
      params.require(:fileupload).permit(:title, :description, :upload, :slug, :language_id, :sort)
    end

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:language_type)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:home, :show, :index]
	before_action :find_post, only: [:show, :edit, :update, :destroy]


  def home
    @posts=Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def index
  	@posts=Post.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)

  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def show
  end

  def update
  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post.destroy
  	redirect_to posts_home_path
  end


  private

    def find_post
    	@post = Post.friendly.find(params[:id])
    end

    def post_params
    	params.require(:post).permit(:title, :body, :slug)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end


  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/fileuploads_helper.rb
module FileuploadsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/fileuploads/_display.html.erb
<section>

	<h1><%= @fileupload.title  %></h1>

	<br><br>

	<%= @fileupload.description %>

	<br><br>

  <% unless @fileupload.code.url.nil? %>
	  <%= link_to "View source", @fileupload.code.url, class: "ui inverted violet button", download:true %>
  <% end %>


	<br><br>

	<% if user_signed_in? %>
		<%= link_to "Edit file", edit_fileupload_path(@fileupload), class: "ui inverted violet button" %>
		<%= link_to "Delete", fileupload_path(@fileupload), method: :delete, data: { confirm: "Are you sure you wish to delete this post?"}, class: "ui inverted violet button" %>
		<%= link_to "New Language ", languages_path(@languages), method: :create, class: "ui inverted violet button" %>

	<% end %>
	
</section>

app/views/fileuploads/_displayall.html.erb
<div class="ui container">
      
  <div class="ui inverted segment">
    <h1 class="ui large centered inverted violet header">Stuff I have made.</h1>
    <br>
    <h3 class="ui floated small inverted violet header" > by Bree Durbin </h3>
    <% if user_signed_in? %>
      <div class="floated" align="right">
        <% if user_signed_in? %>
          <%= link_to "New File Upload", new_fileupload_path(@fileupload), class: "ui inverted violet button" %>
          <%= link_to "New Language ", new_language_path(@languages), class: "ui inverted violet button" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="ui three cards">

  <% @fileuploads.each do |fileupload| -%>

  <div class="purple card">

    <div class="content">
      <div class="center aligned header"><%= fileupload.title %></div>
      <div class="left aligned description">

        <p><%= fileupload.description %></p>
      </div>
    </div>

    <div class="extra content">
      <div class="left floated">
        <% if user_signed_in? %>
          <%= link_to "Edit file", edit_fileupload_path(fileupload), class: "ui inverted violet button" %>
          <%= link_to "Delete", fileupload_path(fileupload), method: :delete ,data: { confirm: "Are you sure you wish to delete this fileupload?"}, class: "ui inverted violet button" %>
        <% end %>

        <% if fileupload.upload.attached? %>
          <%= link_to "Get source", fileupload.upload, class: "ui inverted violet button", download:true %>
        <% end %>

      </div>

      <span class="right floated">
        <%= fileupload.created_at.strftime('%I:%M %p, %b %d ,%Y') %>
      </span>
    </div>
  </div>

  <% end -%>  

  </div>
</div>

app/views/fileuploads/_form.html.erb
<%= form_for @fileupload do |f| %>

<% if @fileupload.errors.any? %>
<h2><%= pluralize(@fileupload.errors.count, "error") %> Prevented file from uploading:</h2>
<ul>
	<% @fileupload.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<div class="ui inverted segment">
	<div class="ui inverted form">
		<div class="field">
			<%= f.label :language %>
			<%= f.collection_select :language_id, Language.all, :id, :language_type, {}, { :multiple => false }%>
		</div>
		<div class="field">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class="field">
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
		<div class="field">
			<%= f.label :upload%>
			<%= f.file_field :upload, 
				multiple: false,
                direct_upload: true %>
		</div>
		<%= f.submit 'Create', class: "ui inverted violet submit button" %>
	</div>
</div>


<% end %>

app/views/fileuploads/edit.html.erb
<h1 class="text-box"> Edit file </h1>

<%= render 'form' %>

app/views/fileuploads/index.html.erb
<div class="ui visible inverted vertical sidebar accordion menu">
      
	<% if user_signed_in? %>
	<li class="link item">
	<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
	<% else %>
	<li class="link item">
	<%= link_to 'Login', new_user_session_path %>
	</li>
	<% end %>


	<li class="link item"><%= link_to "Home", posts_home_path %> </li>
	<li class="link item"><%= link_to "About me", pages_aboutMe_path %></li>

	<li class="link item"><%= link_to "All", fileuploads_index_path %></li>

	<% Language.all.each do |language| %>
        <li class="link item"> <%= link_to language.language_type, by_language_fileuploads_path(:sort => language.id)%> </li>
    <% end %>
    
  	
</div>
  <div class="pusher">
    <div class="ui container">
      

      <%= render 'displayall' %>



		<%= will_paginate @fileuploads %>
    </div>

</div>

app/views/fileuploads/new.html.erb
<h1> New File </h1>

<%= render 'form' %>

app/views/fileuploads/show.html.erb
<section>

	<%= render 'display' %>

</section>

app/views/languages/_form.html.erb
<%= form_for(language) do |f| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language_type %>
    <%= f.text_field :language_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Languages</h1>

<table>
  <thead>
    <tr>
      <th>Language type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.language_type %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language type:</strong>
  <%= @language.language_type %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>BreeDurbin.me</title>
	<meta charset="utf-8">
	<meta name="from zero to space this website is space" content="from zero to space this website is space">

	<%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

</head>
  <body>


    

    <!-- /.notices from "devises" gem. See readme file. -->
    <% if alert %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>




    <%= yield %>
      
      


  </body>

</html>

app/views/pages/aboutMe.html.erb
<div class="ui visible inverted vertical sidebar menu">
      
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "link item"  %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "link item" %>
      <% end %>

      <li class="link item"><%= link_to "Home", posts_home_path %> </li>
      <li class="link item"><%= link_to "File Uploads", fileuploads_path %></li>

  </div>

  <div class="pusher">
    <div class="ui container">

      <div class="ui padded black inverted segment">
        <h1 class="ui large centered inverted violet header">About me</h1>
      </div>

      <div class="ui fluid purple card">
        <div class="content">

          

          <div class="description">

           <p>
            <b>About me:</b>
            <p>
            Hi, my name is Bree Durbin and I am a software Engineer. I recently graduated from UCCS (May 2018) with a BS: Mathematics with a concentration in computer science. My favorite languages are Ruby for simple web dev, c# for gui and general purpose stuff and Java for enterprise webservices. I also have an interest in Python and C++.
            When I have free time I spend it teaching myself various programming languages and reading mathematics or science papers.(I am a pretty boring person, Sorry.)
            I also enjoy anime and pen and paper roleplaying games. Two of the languages I have taught myself are Ruby and C#. This website is written in Rails with embedded Ruby.
            </p>

            <%= image_tag "about_me.jpg", :class => "right floated ui small image" %>

            <p><br>
              I am currently working at Boeing as a software engineering Intern. I did c# development for them for my first 3 months. For the next 8 I did integration and automation for our microservices backend which runs in a docker swarm I setup. I also did all of the initial scripting for deployment and much of our build scripts. Many of my deployment scripts are still used today via Jenkins. Since around Janruary 2017 I have been working backend services writing restful webservices based around Spring and Jersey.
              
              Before working at Boeing I was a C# developer for an ecommerce firm
              named Engine23. I did back end development for them for an electrocardiogram app.
            </p><br>
            <p>
            Programming fields of interest:
              </p>
              <p>Big Data, Cloud Computing, algorithms, and Full Stack Web Development.
            </p><br>
            <p>
            Mathematical interests: Linear algebra, Statistics, Optimization.
            </p>
          </div>
        </div>
      </div>

    </div>

</div>









    


 

app/views/pages/fileArchive.html.erb
<div class="container">	
	<% @fileuploads.each_slice(3) do |slice| %>
		<div class="row">
			<% slice.each do |fileupload| %>
				
				<div class="col-md-4 text-box">
					<br><br>
					<h3><%= fileupload.section %></h3>

					<br><br>

					<div><%= fileupload.title %></div>

					<br><br>

					<div><%= fileupload.description %></div>

					<br><br>

					<div class="btn btn-warning"><%= fileupload.source %></div>

					<br><br>

					<div><%= fileupload.bin %></div>

					<br><br>

					<%= link_to "Edit file", edit_fileupload_path(fileupload) %>

					<%= link_to "Delete", fileupload_path(fileupload), method: :delete, data: { confirm: "Are you sure you wish to delete this post?"} %>
				</div>

			<% end -%>
		</div>
	<% end -%>
</div>


<br><br>
	<div class="col-md-4 border">
		<a href="codeSamples/brian_resume.docx" class="btn btn-warning">My resume</a>
		<br>
		<span class="text-box">My resume in word format.
		</span>
		<br><br><br>
		<a href="codeSamples/HW1_Durbin.asm" class="btn btn-warning">Simple Array Fill</a>
		<br>
		<span class="text-box">First assembly project: Initializes an array with a loop 
		because it needed to be done the circumvoluted way.
		</span>
	</div>
	<div class="col-md-4">
		<a href="codeSamples/HW2_Durbin.asm" class="btn btn-warning">XOR Cipher Decrypter</a>
		<br>
		<span class="text-box">Iterates through the bytes of an array 
		and xors them; basic XOR encrypter/decrypter.
		</span>
		<br><br><br>
		<a href="codeSamples/main.c" class="btn btn-warning">Command-line Blackjack</a>
		<br>
		<span class="text-box">Second project in my old C class. Super simple blackjack in c.
		</span> 
	</div>
	<div class="col-md-4">
		<a href="codeSamples/backup.txt" class="btn btn-warning">C Shell File Backup</a>
		<br>
		<span class="text-box">Backs up all the files listed in a 
		file($arg1) to a folder of your naming($arg2)
		</span>
		<br><br><br>
		<a href="codeSamples/softLinkFinder.txt" class="btn btn-warning">C Shell Soft-Link Finder</a>
		<br>
		<span class="text-box">Finds all the soft-links in a directory via 
		the command 'ls -l | grep ^l | grep "\-> $argv[1]"''
		</span>
	</div>
</div>
<br><br>
	<span class="text-box">This is by no means even close to the extent of my coding ability,
	 unfortunately my more interesting programs are stuck on my server that is in storage for
	  now so I cant get them up on this site quite yet.Sorry. :(</span>
<br><br><br><br><br>

app/views/pages/home.html.erb
	
<div class="container">
	<div class="row">
		<div class="col-lg-12 text-box">
			<h4 class="text-box" align="center" style="color:#2d7eff">Web development and programming projects by Brian Durbin</h4>
			<div class="col-lg-3 text-box">
				<p>
					Welcome to Nonlinear Logic; a website created to showcase some of my web design and programming skills.

				</p>

				<p>
					For examples of my code:
					<a href="fileArchive.php" class="btn btn-warning">Click here</a>
					<br><br><br>

					To learn more about me:   
					<a href="aboutMe.php" class="btn btn-warning">Click here</a>
					<br><br><br>

					Connect to my Linkedin:   
					<a href="https://www.linkedin.com/profile/preview?vpa=pub&locale=en_US" 
					class="btn btn-warning"><i class="fa fa-linkedin-square">Click here</i></a>
					<br><br><br>
				</p>

				<br><br><br>
			</div>
			<div class="col-lg-9 text-box">
				<!--blog here -->
			</div>
		</div>
			
	</div>
</div>
		




	

app/views/posts/_display.html.erb
  <div class="ui purple fluid card">

    <div class="image">
      <%= image_tag("backgroundpost1.png", :alt => "") %>
      <!--<img url="background2.jpg" alt="">-->
    </div>

    <div class="content">
      <div class="center aligned header"><%= @post.title %></div>
      <div class="left aligned description">
        <%= @post.body %>
      </div>
    </div>

    <div class="extra content">
      <div class="left floated">
        <% if user_signed_in? %>
            <%= link_to "Edit Post", edit_post_path(@post), class: "ui inverted violet button" %>
            <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you wish to delete this post?"}, class: "ui inverted violet button" %>
        <% end %>
      </div>

      <span class="right floated">
        <%= @post.created_at.strftime('%I:%M %p, %b %d ,%Y') %>
      </span>
    </div>

    

  </div>

app/views/posts/_displayall.html.erb
<% backgrounds = ["backgroundpost1.png","backgroundpost2.png","backgroundpost3.png"] %>



<% @posts.each_with_index do |post, idx| %>

  <div class="ui purple fluid card">

    <div class="image">
      <%= image_tag(backgrounds[idx % 3], :alt => "") %>
    </div>


    <div class="content">
      <div class="center aligned header"><%= post.title %></div>
      <div class="left aligned description">
        <%= markdown(post.body) %>
      </div>
    </div>

    <div class="extra content">
      <div class="left floated">
        <%= link_to "View full post.", post, class: "ui inverted violet button" %>
        <% if user_signed_in? %>
            <%= link_to "Edit Post", edit_post_path(post), class: "ui inverted violet button" %>
            <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure you wish to delete this post?"}, class: "ui inverted violet button" %>
        <% end %>
      </div>

      <span class="right floated">
        <%= post.created_at.strftime('%I:%M %p, %b %d ,%Y') %>
      </span>
    </div>
  </div>

  

<% end %>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
var disqus_shortname = 'nonlinearlogic';
var disqus_title = '<%= @post.title %>';


var disqus_config = function () {
var disqus_url = '<%= url_for([@post, {only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
var disqus_identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//nonlinearlogic.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<h2><%= pluralize(@post.errors.count, "error") %> Prevented this post from saving:</h2>
	<ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

  <%= f.label :title, :class => 'text-box' %><br>
  <%= f.text_field :title, :class => 'form-box' %><br>

  <%= f.label :body, :class => 'text-box' %><br>
  <%= f.text_area :body, :class => 'form-description-box'  %><br>


	<%= f.submit 'Post', class: "ui inverted violet button" %>
<% end %>

app/views/posts/edit.html.erb
<h1 class="text-box center"> Edit Post </h1>

<%= render 'form' %>

app/views/posts/home.html.erb
<div class="ui visible inverted vertical sidebar accordion menu">
      
      <% if user_signed_in? %>
        <li class="link item">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
      <li class="link item">
        <%= link_to 'Login', new_user_session_path %>
      </li>
      <% end %>

      <li class="link item"><%= link_to "File Uploads", fileuploads_path %></li>
      <li class="link item"><%= link_to "About me", pages_aboutMe_path %></li>

      <div class="item">
        <div class="link dropdown title">
          Webcomics
        </div>
        <div class="content link items">
          <a class="item" href="http://www.giantitp.com/Comics.html">Order of the Stick</a>
          <a class="item" href="http://www.smbc-comics.com/index.php?id=3940">Saturday Morning Breakfast Cereal</a>
          <a class="item" href="http://xkcd.com/">XKCD</a>
          <a class="item" href="http://abstrusegoose.com/12">Abstruse Goose</a>
        </div>
      </div>
        
      <div class="item">
        <div class="link dropdown title">
          Mathematics
        </div>
        <div class="content link items">
          <a class="item" href="https://terrytao.wordpress.com/">Terrence Tao's Mathematics Blog</a>
        </div>
      </div>
  </div>
  <div class="pusher">
    <div class="ui container">
      
      <div class="ui inverted segment">
        <h1 class="ui large centered inverted violet header">Programming, Mathematics, Science and other nerdery.</h1>
        <br>
        <h3 class="ui floated small inverted violet header" > by Bree Durbin </h3>
        <% if user_signed_in? %>
          <div class="floated" align="right">
            <%= link_to "New post", new_post_path(@post), class: "ui inverted violet button" %>
          </div>
      <% end %>
      </div>

      

      <%= render 'displayall' %>

      <%= will_paginate @posts %>
    </div>

</div>

    

app/views/posts/new.html.erb
<h1 class="text-box center"> New Post </h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render 'display' %>


<%= render 'disqus' %>